name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Unittests
      run: dotnet test
